[pytest]
asyncio_default_test_loop_scope = session
asyncio_mode = auto
python_files = test_*.py
addopts = -vvv --tb=short --maxfail=3 -s --html=reports/pytest_async_playwright_report.html --self-contained-html
log_cli = true
log_cli_level = INFO